name: Exécuter Script PowerShell Quotidien 

on:

  workflow_dispatch: # Ajoute l'exécution manuelle

jobs:
  run-powershell:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Installer les dépendances PowerShell
        run: |
          Install-Module -Name ImportExcel -Force -Scope CurrentUser -ErrorAction Stop
        shell: powershell
      - name: Exécuter le script PowerShell
        run: |
          ./horraire.ps1
        shell: powershell
