name: Exécuter Script PowerShell Quotidien 

on:
  schedule:
    - cron: '15 13 * * *' # 7h30 Québec en EDT
    - cron: '30 11 * * *' # 7h30 Québec en EDT (11h30 UTC)
  workflow_dispatch: # Ajoute l'exécution manuelle

jobs:
  run-powershell:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Installer les dépendances PowerShell
        run: |
          Install-Module -Name ImportExcel -Force -Scope CurrentUser -ErrorAction Stop
        shell: powershell
      - name: Exécuter le script PowerShell
        run: |
          ./horraire.ps1
        shell: powershell
