name: Spordle Facebook Publisher

on:
  # Exécution manuelle
  workflow_dispatch:
    inputs:
      test_date_offset:
        description: 'Nombre de jours à partir d\'aujourd\'hui (0=aujourd\'hui, 1=demain, etc.)'
        required: false
        default: '0'
        type: string
      
  # Exécution automatique tous les jours à 7h00 EST
  schedule:
    - cron: '0 12 * * *'  # 12:00 UTC = 7:00 EST (8:00 EDT en été)

jobs:
  publish-spordle-matches:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Install Chrome and dependencies
      run: |
        # Installer Chrome
        wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
        
        # Installer les dépendances pour les images
        sudo apt-get install -y libjpeg-dev zlib1g-dev
        
    - name: Create directories
      run: |
        mkdir -p commanditaire
        mkdir -p temp
        
    - name: Configure date for testing (if manual trigger)
      if: github.event_name == 'workflow_dispatch'
      run: |
        echo "DATE_OFFSET=${{ github.event.inputs.test_date_offset }}" >> $GITHUB_ENV
        
    - name: Configure date for scheduled run
      if: github.event_name == 'schedule'
      run: |
        echo "DATE_OFFSET=0" >> $GITHUB_ENV
        
    - name: Run Spordle Facebook script
      env:
        SPORDLE_PASS: ${{ secrets.SPORDLE_PASS }}
        FACEBOOK_PAGE_ID: ${{ secrets.FACEBOOK_PAGE_ID }}
        FACEBOOK_ACCESS_TOKEN: ${{ secrets.FACEBOOK_ACCESS_TOKEN }}
        DISPLAY: :99
      run: |
        # Démarrer un serveur X virtuel pour Chrome
        sudo Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
        sleep 3
        
        # Exécuter le script
        python spordle_facebook.py
        
    - name: Upload debug files on failure
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: debug-files
        path: |
          temp/spordle_games_debug.html
          spordle_facebook.log
        retention-days: 7
        
    - name: Upload logs on success
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: success-logs
        path: spordle_facebook.log
        retention-days: 3
