name: Spordle Facebook Publisher Python

on:
  workflow_dispatch:

jobs:
  publish-spordle-matches:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Install Chrome and dependencies
      run: |
        # Installer Chrome
        wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
        
        # Installer les dépendances pour les images
        sudo apt-get install -y libjpeg-dev zlib1g-dev xvfb
        
    - name: Diagnostic Chrome installations
      run: |
        echo "=== Diagnostic des installations Chrome ==="
        echo "Recherche de tous les binaires Chrome:"
        find /usr /opt -name "*chrome*" -type f 2>/dev/null | head -10
        echo ""
        echo "Versions trouvées:"
        for chrome in /usr/bin/google-chrome /usr/bin/google-chrome-stable /opt/google/chrome/chrome; do
          if [ -f "$chrome" ]; then
            echo "$chrome: $($chrome --version 2>/dev/null || echo 'erreur')"
          fi
        done
        echo ""
        echo "Processus Chrome en cours:"
        ps aux | grep chrome | head -5
        
    - name: Synchronize ChromeDriver
      run: |
        echo "=== Synchronisation ChromeDriver ==="
        python3 sync_chromedriver.py
        
    - name: Create temp directory
      run: |
        mkdir -p temp
        
    - name: Run Spordle Facebook script
      env:
        SPORDLE_PASS: ${{ secrets.SPORDLE_PASS }}
        FACEBOOK_PAGE_ID: ${{ secrets.FACEBOOK_PAGE_ID }}
        FACEBOOK_ACCESS_TOKEN: ${{ secrets.FACEBOOK_ACCESS_TOKEN }}
        DISPLAY: :99
      run: |
        # Démarrer un serveur X virtuel pour Chrome
        xvfb-run -a --server-args="-screen 0 1920x1080x24" python spordle_facebook.py
        
    - name: Upload logs on failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: error-logs
        path: |
          temp/
          *.log
        retention-days: 7
